#!/usr/bin/env sh
set -x
if [ -e /usr/local/bin/glibtoolize ] ; then
   /usr/local/bin/glibtoolize --force
elif [ -e /usr/bin/glibtoolize ] ; then
   /usr/bin/glibtoolize --force
elif [ -e /usr/local/bin/libtoolize ] ; then
   /usr/local/bin/libtoolize --force
elif [ -e /usr/bin/libtoolize ] ; then
   /usr/bin/libtoolize --force
fi
if [ -e /usr/local/share/aclocal ] ; then
   aclocal -I /usr/local/share/aclocal
else
   aclocal
fi
autoheader
autoconf
automake --foreign --add-missing --copy
